function [fitresult, gof] = createFit(gap, no,neff)
%CREATEFIT(GAP,NO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : gap
%      Y Output: no
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Feb-2023 17:50:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( gap, no );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+neff', 'independent', 'x', 'dependent', 'y' ,'problem','neff');
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.StartPoint = [0.12 0.012];
opts.TolFun = 1e-08;
opts.TolX = 1e-08;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'no vs. gap', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel gap
ylabel no
grid on


